PACKAGE_NAME="innogpu-kernel"
PACKAGE_VERSION="2.2"
PROCS_NUM=`nproc`
[ $PROCS_NUM -gt 16 ] && PROCS_NUM=16
MAKE[0]="'make' -j $PROCS_NUM KERNELDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean KERNELDIR=/lib/modules/${kernelver}/build"
BUILT_MODULE_NAME[0]="innogpu"
DEST_MODULE_LOCATION[0]="/kernel/drivers/gpu/drm/innogpu/"
AUTOINSTALL="yes"
PRE_INSTALL="dkms.pre_install $kernelver"
POST_REMOVE="dkms.post_remove $kernelver"
