INNOGPU_INCLUDE :=-I$(INNOGPU_PRO_PATH)/innogpu
INNOGPU_OBJS = \
innogpu/hal_interface.o \
innogpu/hal_bind_numa.o \
innogpu/hal_power.o \
innogpu/hal_dma.o \
innogpu/inno_cpumask.o \
innogpu/inno_dma.o \
innogpu/inno_dma_buf.o \
innogpu/inno_drm.o \
innogpu/inno_audio.o \
innogpu/inno_drm_mode.o \
innogpu/inno_fence.o \
innogpu/inno_firmware.o \
innogpu/inno_fs.o \
innogpu/inno_idr.o \
innogpu/inno_interrupt.o \
innogpu/inno_io.o \
innogpu/inno_lock.o \
innogpu/inno_misc.o \
innogpu/inno_mm.o \
innogpu/inno_mtrr.o \
innogpu/inno_pci.o \
innogpu/inno_plat_dev.o \
innogpu/inno_task.o \
innogpu/inno_timer.o \
innogpu/inno_uaccess.o \
innogpu/inno_waitqueue.o \
innogpu/inno_math.o \
innogpu/inno_pm_runtime.o \
innogpu/inno_debug.o \
innogpu/kernel_compat.o \
innogpu/innogpu_pci_drv.o \
innogpu/inno_insn.o \
innogpu/inno_kernel_hook.o \
innogpu/inno_uuid.o \
innogpu/inno_check.o \
innogpu/innogpu.o

  INNOGPU := $(INNOGPU_OBJS)
